sudo: required
services:
  - docker

before_install:
  - docker build -t sijil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sijil/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-react"
  env: "Docker-env"
  bucket_name: ""
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
